# readthedocs now requires that you barf this into your project root or else it will refuse to function
version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
sphinx:
  configuration: docs/conf.py
