version: 2.1
jobs:
  run-tests:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run:
          name: "Install test deps"
          command: "pip install .[test]"
      - run:
          name: "Install codecov"
          command: "pip install codecov"   
      - run:
          name: "Run tests"
          command: "python setup.py pytest"
      - store_test_results:
          path: test
      - run:
          name: "Notify codecov"
          command: "codecov"
workflows:
  run-tests-workflow:
    jobs:
      - run-tests
